name: chassis-demo
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jupyter
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - parso=0.8.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0
  - pygments=2.7.1
  - python=3.8.12
  - python-dateutil=2.8.1
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pyzmq=19.0.2
  - readline=8.1
  - setuptools=58.0.4
  - six=1.15.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - pip:
    - alembic==1.4.1
    - charset-normalizer==2.0.7
    - chassisml==0.0.2
    - click==8.0.3
    - cloudpickle==2.0.0
    - databricks-cli==0.16.2
    - docker==5.0.3
    - entrypoints==0.3
    - flask==2.0.2
    - gitdb==4.0.9
    - gitpython==3.1.24
    - greenlet==1.1.2
    - gunicorn==20.1.0
    - idna==3.3
    - importlib-metadata==4.8.2
    - itsdangerous==2.0.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - mako==1.1.5
    - markupsafe==2.0.1
    - mlflow==1.21.0
    - numpy==1.21.4
    - opencv-python-headless==4.5.4.58
    - packaging==21.2
    - pandas==1.3.4
    - prometheus-client==0.12.0
    - prometheus-flask-exporter==0.18.5
    - protobuf==3.19.1
    - pyparsing==2.4.7
    - python-editor==1.0.4
    - pytz==2021.3
    - pyyaml==6.0
    - querystring-parser==1.2.4
    - requests==2.26.0
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - smmap==5.0.0
    - sqlalchemy==1.4.27
    - sqlparse==0.4.2
    - tabulate==0.8.9
    - threadpoolctl==3.0.0
    - urllib3==1.26.7
    - websocket-client==1.2.1
    - werkzeug==2.0.2
    - zipp==3.6.0