apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaniko-data
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
