apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.K_DATA_VOLUME_NAME }}
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Delete
