{{- if eq .Values.storage.provider "pv" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. This is used in deployment.
  name: {{ include "chassis.fullname" . }}-kaniko-data-pvc
spec:
  storageClassName: ""
  accessModes:
    # The volume is mounted as read-write by a single node
    - ReadWriteOnce
  volumeName: {{ include "chassis.fullname" . }}-kaniko-data-pv
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "chassis.fullname" . }}-kaniko-data-pv
  labels:
    type: local
spec:
  storageClassName: ""
  claimRef:
    name: {{ include "chassis.fullname" . }}-kaniko-data-pvc
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: {{ .Values.storage.size | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.hostPath }}
{{- end }}
