{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chassis.serviceAccountName" . }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "secrets"]
    verbs: ["get", "create", "list", "delete", "watch"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs", "pods"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: {{ include "chassis.serviceAccountName" . }}
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: {{ include "chassis.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  apiGroup: rbac.authorization.k8s.io
  kind: Role #this must be Role or ClusterRole
  name: {{ include "chassis.serviceAccountName" . }}
{{- end }}
