apiVersion: v1
kind: Secret
metadata:
  name: storage-key
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob .Values.CREDENTIALS_FILEPATH }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}