version: "3.9"
services:
  model-importer:
    container_name: model-importer
    build:
      context: ../model-importer
      dockerfile: Dockerfile.local
    # build: https://${MODZY_USERNAME}:${MODZY_PASSWORD}@github.modzy.engineering/modzy-platform/model-importer.git#0.7.204
    environment:
      - SP_ACCESS_KEY_ID
      - SP_SECRET_ACCESS_KEY
      - MODZY_IMPORTER_BUCKET_NAME
      - MODZY_IMPORTER_JDBC_URL
      - MODZY_IMPORTER_JDBC_USER
      - MODZY_IMPORTER_JDBC_PASSWORD
      # - RS_SERVER_PORT=80
    ports:
      - 2025:2025
    networks:
      - local-network

  model-converter:
    container_name: model-converter
    depends_on:
      - model-importer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MODZY_MI_HOST
      - MODZY_MI_PORT
      - MODZY_MC_ECR_REGISTRY
      - MODZY_MC_ECR_REPO
      - MODZY_MC_ECR_USER
      - MODZY_MC_DIR
      - MODZY_EXEC_ENVIRONMENT
      - AWS_SHARED_CREDENTIALS_FILE=/kaniko/.aws/credentials
      - DOCKER_CONFIG=/kaniko/.docker
      - AWS_SDK_LOAD_CONFIG=true

      # - MODZY_MC_SM_BUCKET
      # - MODZY_MC_RES_PATH
      # - MODZY_MC_PARAMS_PATH
      # - MODZY_MC_MODEL_TYPE
    ports:
      - 8080:8080
    networks:
      - local-network

#  sagemaker-notebook:
#    container_name: sagemaker-notebook
#    depends_on:
#      - model-converter
#    build:
#      # context: https://${MODZY_USERNAME}:${MODZY_PASSWORD}@github.modzy.engineering/modzy-models/data-science-solutions.git:notebooks/sagemaker_demo/Dockerfile
#      context: ../../PycharmProjects/data-science-solutions/notebooks/sagemaker_demo
#    ports:
#      - 10000:10000
#    environment:
#      - AWS_ACCESS_KEY_ID
#      - AWS_SECRET_ACCESS_KEY
#      - MODZY_BASE_URL
#      - MODZY_API_KEY
#    networks:
#      - local-network

networks:
  local-network:
    driver: bridge
