apiVersion: v1
kind: Pod
metadata:
  name: modzy-builder-api
spec:
  serviceAccountName: job-robot
  restartPolicy: OnFailure
  volumes:
  - name: minio-pv-claim
    persistentVolumeClaim:
      claimName: minio-pv-claim
  containers:
  - image: modzy-builder-api:0.0.1
    imagePullPolicy: Never
    name: modzy-builder-api
    volumeMounts:
    - mountPath: /modzy
      name: minio-pv-claim
