apiVersion: v1
kind: Service
metadata:
#  name: {{ include "chassis.fullname" . }}
  name: chassis-serv
  labels:
    {{- include "chassis.labels" . | nindent 4 }}
spec:
#  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.PORT }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chassis.selectorLabels" . | nindent 4 }}
