site_name: Chassis
nav:
    - index.md
    - Tutorials:
        - tutorials/devops-deploy.md
        - tutorials/ds-connect.md
        - tutorials/ds-deploy.md
        - tutorials/devops-cli.md
    - About: about.md
theme: material
